---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: delegated
  options:
    managed: false
platforms:
  - name: node2
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          node2:
            ansible_host: 192.168.60.2
            ansible_password: molecule
  config_options:
    defaults:
      retry_files_enabled: false
      deprecation_warnings: false
      host_key_checking: false
      gathering: 'explicit'
verifier:
  name: ansible
