---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_host: 'localhost'
      ansible_connection: 'local'
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
      deprecation_warnings: false
      gathering: 'explicit'
verifier:
  name: 'ansible'
