---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: vagrant
  provider:
    # Can be any supported provider (virtualbox, parallels, libvirt, etc)
    # Defaults to virtualbox
    name: virtualbox
  provision: false
  cachier: machine
  parallel: true
  default_box: 'generic/alpine310'
platforms:
  - name: node1
    hostname: node1.local
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - network_name: forwarded_port
        guest: 80
        host: 8080
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "uname"'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
    box: "almalinux/8"
    box_version: 8.6.20220802
    memory: 512
    cpus: 1
  - name: node2
    hostname: node2.local
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - network_name: forwarded_port
        guest: 80
        host: 8081
    instance_raw_config_args:
      - 'vm.provision :shell, inline: "uname"'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
    box: "almalinux/8"
    box_version: 8.6.20220802
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
      deprecation_warnings: false
      gathering: 'explicit'
verifier:
  name: ansible
