---
name: 'Molecule Tests'
on:
  - 'push'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      max-parallel: 5
      matrix:
        python-version:
         - '3.9'
         - '3.10'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip3 install tox

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-${{ matrix.python }}-toxcache

      - name: Test with tox
        run: tox
